from dataclasses import dataclass, field
from typing import Dict, List
import pandas as pd


@dataclass(frozen=True)
class UnifiedAdsSchema:
    """
    Defines what a valid unified ads analytics table must contain.
    Only validation rules live here.
    """
    # List of columns that MUST exist after normalization
    required_columns: List[str] = field(default_factory=lambda: [
        "date",             # For time-analyze
        "platform",         # To aggregate multiple rows of data into summarized results
        #"campaign_name",    # To compare platforms
        "campaign_type",    # To no the goal of it
        "impressions",      # To compute CTR
        "clicks",           # To compute CPC or CVR
        "spend"             # To compute CPA or ROAS
    ])

    # Columns that must be numeric for metric calculations
    # conversions How many times the desired action happened.
    # conversion_valueThe total financial value generated by those conversions.
    numeric_columns: List[str] = field(default_factory=lambda: [
        "impressions",
        "clicks",
        "spend",
        "conversions",
        "conversion_value",
        "reach",
        "frequency",
    ])

    # Unified aliases that sometimes appear after platform exports or manual preprocessing.
    # These are normalized to the canonical names used in this project.
    unified_aliases: Dict[str, str] = field(default_factory=lambda: {
        "day": "date",
        "report_date": "date",
        "campaign": "campaign_name",
        "campaignname": "campaign_name",
        "campaign title": "campaign_name",
        "campaign type": "campaign_type",
        "impr.": "impressions",
        "impr": "impressions",
        "click": "clicks",
        "cost": "spend",
        "amount spent": "spend",
        "amount spent (usd)": "spend",
        "results": "conversions",
        "purchases": "conversions",
        "conv value": "conversion_value",
        "conversion value": "conversion_value",
    })

    def validate_required(self, df: pd.DataFrame) -> None:
        missing = [c for c in self.required_columns if c not in df.columns]
        if missing:
            raise ValueError(f"Missing required unified columns: {missing}")
            # Check numeric columns
        self.validate_numeric_types(df)
        
    def validate_numeric_types(self, df: pd.DataFrame) -> None:
        """
        Ensures numeric columns contain numeric values.
        Raises error if non-numeric values are detected.
        """
        non_numeric_columns = []

        for col in self.numeric_columns:
            if col in df.columns:
                # Try coercion without modifying original df
                converted = pd.to_numeric(df[col], errors="coerce")

                # If original had non-null values that became NaN → invalid numeric
                invalid_mask = df[col].notna() & converted.isna()

                if invalid_mask.any():
                    non_numeric_columns.append(col)

        if non_numeric_columns:
            raise ValueError(
                f"Non-numeric values detected in columns: {non_numeric_columns}"
            )

    def canonicalize_column_name(self, column: str) -> str:
        """
        Converts a column header into the canonical unified name when an alias is known.
        Unknown names are returned unchanged.
        """
        raw = str(column).strip()
        key = raw.lower()
        return self.unified_aliases.get(key, raw)


    def canonicalize_columns(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Normalizes already-unified/partially-unified headers (e.g., 'cost' -> 'spend').
        This is intentionally safe: only known aliases are renamed.
        """
        df = df.copy()
        rename_map = {col: self.canonicalize_column_name(col) for col in df.columns}
        # protect against duplicates created by renaming (e.g., "Cost" -> "spend" when "spend" already exists)
        if df.columns.duplicated().any():
            df = df.loc[:, ~df.columns.duplicated(keep="last")]

        return df